const $=id=>document.getElementById(id);let db=null;const C=window.LUA_LOCKER_CONFIG||{};$("url").value=localStorage.getItem("ll_url")||C.SUPABASE_URL||"";$("key").value=localStorage.getItem("ll_key")||C.SUPABASE_PUBLISHABLE_KEY||"";
function valid(v){try{let u=new URL(v);return u.protocol==="https:"&&u.hostname.endsWith(".supabase.co")}catch{return false}}
function msg(e,t,ok=false){e.textContent=t;e.style.color=ok?"#86efac":"#fbbf24"}
function make(){let u=$("url").value.trim(),k=$("key").value.trim();if(!valid(u))return msg($("setupMsg"),"❌ Project URL không đúng.");if(k.length<20)return msg($("setupMsg"),"❌ Publishable key chưa đúng.");localStorage.setItem("ll_url",u);localStorage.setItem("ll_key",k);db=supabase.createClient(u,k,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return true}
async function show(){if(!db)return;let {data}=await db.auth.getSession(),s=data.session;if(s){$("login").classList.add("hidden");$("settings").classList.add("hidden");$("app").classList.remove("hidden");$("logout").classList.remove("hidden");$("user").textContent=s.user.email||"Tài khoản"}else{$("app").classList.add("hidden");$("login").classList.remove("hidden");$("logout").classList.add("hidden")}}
function ready(){if(db)return true;if(!make()){$("login").classList.add("hidden");$("settings").classList.remove("hidden");return false}return true}
$("save").onclick=async()=>{if(make()){msg($("setupMsg"),"✅ Đã kết nối.",true);$("settings").classList.add("hidden");$("login").classList.remove("hidden");await show()}}
$("back").onclick=()=>{$("settings").classList.add("hidden");$("login").classList.remove("hidden")}
$("configBtn").onclick=()=>{$("app").classList.add("hidden");$("login").classList.add("hidden");$("settings").classList.remove("hidden")}
$("loginBtn").onclick=async()=>{if(!ready())return;let e=$("email").value.trim(),p=$("password").value;if(!e||!p)return msg($("authMsg"),"❌ Nhập email và mật khẩu.");msg($("authMsg"),"Đang đăng nhập...");let {data,error}=await db.auth.signInWithPassword({email:e,password:p});if(error)return msg($("authMsg"),"❌ "+error.message);show()}
$("signupBtn").onclick=async()=>{if(!ready())return;let e=$("email").value.trim(),p=$("password").value;if(!e||p.length<6)return msg($("authMsg"),"❌ Mật khẩu phải từ 6 ký tự.");msg($("authMsg"),"Đang tạo tài khoản...");let {data,error}=await db.auth.signUp({email:e,password:p});if(error)return msg($("authMsg"),"❌ "+error.message);if(data.session)show();else msg($("authMsg"),"✅ Đã tạo tài khoản. Hãy xác nhận email rồi đăng nhập.",true)}
$("googleBtn").onclick=async()=>{if(!ready())return;let {error}=await db.auth.signInWithOAuth({provider:"google",options:{redirectTo:location.href}});if(error)msg($("authMsg"),"❌ "+error.message)}
$("logout").onclick=async()=>{await db.auth.signOut();show()}
$("file").onchange=async e=>{let f=e.target.files?.[0];if(!f)return;$("name").value=$("name").value||f.name.replace(/\.[^.]+$/,"");$("slug").value=$("slug").value||f.name.replace(/\.[^.]+$/,"").toLowerCase().replace(/[^a-z0-9_-]/g,"-");$("code").value=await f.text()}
function b64(s){let a=new TextEncoder().encode(s),x="";for(let b of a)x+=String.fromCharCode(b);return btoa(x)}
$("lock").onclick=async()=>{if(!ready())return;let {data:{session}}=await db.auth.getSession();if(!session)return msg($("lockMsg"),"❌ Chưa đăng nhập.");let code=$("code").value;if(!code.trim())return msg($("lockMsg"),"❌ Chưa có code Lua.");let name=$("name").value.trim()||"script",slug=$("slug").value.trim().toLowerCase().replace(/[^a-z0-9_-]/g,"-")||"script-"+Date.now(),secret=crypto.randomUUID().replaceAll("-","");msg($("lockMsg"),"Đang tạo Raw...");let {data,error}=await db.from("scripts").insert({user_id:session.user.id,name,slug,payload:b64(code),key:secret}).select("slug").single();if(error)return msg($("lockMsg"),"❌ "+error.message+"\nChạy supabase/schema.sql trước.");let raw=$("url").value.trim()+"/functions/v1/raw/"+encodeURIComponent(data.slug)+"?k="+secret;$("raw").value=raw;$("loader").textContent=`loadstring(game:HttpGet("${raw}"))()`;$("result").classList.remove("hidden");msg($("lockMsg"),"✅ Tạo Raw thành công.",true)}
$("copyRaw").onclick=async()=>{await navigator.clipboard.writeText($("raw").value);msg($("lockMsg"),"✅ Đã sao chép.",true)};$("copyLoader").onclick=async()=>{await navigator.clipboard.writeText($("loader").textContent);msg($("lockMsg"),"✅ Đã sao chép.",true)}
(async()=>{if(valid($("url").value)&&$("key").value.length>20){make();await show()}else{$("login").classList.add("hidden");$("settings").classList.remove("hidden");msg($("setupMsg"),"⚙️ Nhập cấu hình Supabase một lần.")}if(db)db.auth.onAuthStateChange(()=>show())})();